### ISSUE TITLE
The API key is required for new authorizations.

### ISSUE THREAD

**Issue by kanjvt** [yashoswalyo/MERGE-BOT#28]
i already filled config like that you made https://telegra.ph/file/eae155c2918c9de8d5a55.jpg but i dont know why about this error

2022-07-20T03:20:19.236237+00:00 app[worker.1]: 20-Jul-22 03:20:19 - INFO - Bot started [bot.py:59]
2022-07-20T03:20:19.324943+00:00 app[worker.1]: 20-Jul-22 03:20:19 - INFO - Bot started [bot.py:59]
2022-07-20T03:20:19.611751+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-20T03:20:19.611770+00:00 app[worker.1]:   File "/usr/src/mergebot/bot.py", line 557, in <module>
2022-07-20T03:20:19.612010+00:00 app[worker.1]:     mergeApp.run()
2022-07-20T03:20:19.612012+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/run.py", line 84, in run
2022-07-20T03:20:19.612088+00:00 app[worker.1]:     self.start()
2022-07-20T03:20:19.612090+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
2022-07-20T03:20:19.612153+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2022-07-20T03:20:19.612155+00:00 app[worker.1]:   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
2022-07-20T03:20:19.612279+00:00 app[worker.1]:     return future.result()
2022-07-20T03:20:19.612287+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/start.py", line 58, in start
2022-07-20T03:20:19.612345+00:00 app[worker.1]:     is_authorized = await self.connect()
2022-07-20T03:20:19.612346+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/auth/connect.py", line 40, in connect
2022-07-20T03:20:19.612404+00:00 app[worker.1]:     await self.load_session()
2022-07-20T03:20:19.612412+00:00 app[worker.1]:   File "/usr/local/lib/python3.10/dist-packages/pyrogram/client.py", line 574, in load_session
2022-07-20T03:20:19.612527+00:00 app[worker.1]:     raise AttributeError("The API key is required for new authorizations. "
2022-07-20T03:20:19.612538+00:00 app[worker.1]: AttributeError: The API key is required for new authorizations. More info: https://docs.pyrogram.org/start/auth
2022-07-20T03:20:20.260283+00:00 heroku[worker.1]: State changed from up to crashed
2022-07-20T03:20:20.211410+00:00 heroku[worker.1]: Process exited with status 1

**Comment by yashoswalyo** [comment]
Use TELEGRAM_API instead of API_ID in config file
